-- IconTextureAtlases
INSERT INTO
	IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
VALUES
	('TIBETAN_BUDDHISM_ATLAS', 256, 'TibetanReligionsAtlas_256.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 128, 'TibetanReligionsAtlas_128.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 80, 'TibetanReligionsAtlas_80.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 64, 'TibetanReligionsAtlas_64.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 48, 'TibetanReligionsAtlas_48.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 32, 'TibetanReligionsAtlas_32.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 24, 'TibetanReligionsAtlas_24.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 16, 'TibetanReligionsAtlas_16.dds', 3, 3);

-- IconFontTextures
INSERT INTO
	IconFontTextures (IconFontTexture, IconFontTextureFile)
VALUES
	('ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 'TibetanReligions_FontIcons');

-- IconFontMapping
INSERT INTO
	IconFontMapping (IconName, IconFontTexture, IconMapping)
VALUES
	('ICON_RELIGION_NYINGMA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 8),
	('ICON_RELIGION_KARMA_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 7),
	('ICON_RELIGION_DRIKUNG_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 2),
	('ICON_RELIGION_DRUKPA_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 3),
	('ICON_RELIGION_SAKYA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 9),
	('ICON_RELIGION_GELUK', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 4),
	('ICON_RELIGION_JONANG', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 5),
	('ICON_RELIGION_BON', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 1),
	('ICON_RELIGION_KADAMPA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 6);

	-- Religions
INSERT INTO Religions
	(Type,						Description,						Civilopedia,							IconAtlas,						PortraitIndex,	IconString)
VALUES
	('RELIGION_NYINGMA',		'TXT_KEY_RELIGION_NYINGMA',		'TXT_KEY_RELIGION_NYINGMA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		7,				'[ICON_RELIGION_NYINGMA]'),
	('RELIGION_KARMA_KAGYU',	'TXT_KEY_RELIGION_KARMA_KAGYU',	'TXT_KEY_RELIGION_KARMA_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',		6,				'[ICON_RELIGION_KARMA_KAGYU]'),
	('RELIGION_DRIKUNG_KAGYU',	'TXT_KEY_RELIGION_DRIKUNG_KAGYU',	'TXT_KEY_RELIGION_DRIKUNG_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',	1,				'[ICON_RELIGION_DRIKUNG_KAGYU]'),
	('RELIGION_DRUKPA_KAGYU',	'TXT_KEY_RELIGION_DRUKPA_KAGYU',	'TXT_KEY_RELIGION_DRUKPA_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',		2,				'[ICON_RELIGION_DRUKPA_KAGYU]'),
	('RELIGION_SAKYA',			'TXT_KEY_RELIGION_SAKYA',			'TXT_KEY_RELIGION_SAKYA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		8,				'[ICON_RELIGION_SAKYA]'),
	('RELIGION_GELUK',			'TXT_KEY_RELIGION_GELUK',			'TXT_KEY_RELIGION_GELUK_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		3,				'[ICON_RELIGION_GELUK]'),
	('RELIGION_JONANG',			'TXT_KEY_RELIGION_JONANG',			'TXT_KEY_RELIGION_JONANG_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		4,				'[ICON_RELIGION_JONANG]'),
	('RELIGION_BON',			'TXT_KEY_RELIGION_BON',			'TXT_KEY_RELIGION_BON_PEDIA',			'TIBETAN_BUDDHISM_ATLAS',		0,				'[ICON_RELIGION_BON]'),
	('RELIGION_KADAMPA',		'TXT_KEY_RELIGION_KADAMPA',		'TXT_KEY_RELIGION_KADAMPA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		5,				'[ICON_RELIGION_KADAMPA]');
