INSERT INTO Religions
			(Type,						Description,						Civilopedia,							IconAtlas,						PortraitIndex,	IconString)
VALUES
			('RELIGION_NYINGMA',		'TXT_KEY_RELIGION_NYINGMA',		'TXT_KEY_RELIGION_NYINGMA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		0,				'[ICON_RELIGION_NYINGMA]'),
			('RELIGION_KARMA_KAGYU',	'TXT_KEY_RELIGION_KARMA_KAGYU',	'TXT_KEY_RELIGION_KARMA_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',		1,				'[ICON_RELIGION_KARMA_KAGYU]'),
			('RELIGION_DRIKUNG_KAGYU',	'TXT_KEY_RELIGION_DRIKUNG_KAGYU',	'TXT_KEY_RELIGION_DRIKUNG_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',	2,				'[ICON_RELIGION_DRIKUNG_KAGYU]'),
			('RELIGION_DRUKPA_KAGYU',	'TXT_KEY_RELIGION_DRUKPA_KAGYU',	'TXT_KEY_RELIGION_DRUKPA_KAGYU_PEDIA',	'TIBETAN_BUDDHISM_ATLAS',		3,				'[ICON_RELIGION_DRUKPA_KAGYU]'),
			('RELIGION_SAKYA',			'TXT_KEY_RELIGION_SAKYA',			'TXT_KEY_RELIGION_SAKYA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		4,				'[ICON_RELIGION_SAKYA]'),
			('RELIGION_GELUK',			'TXT_KEY_RELIGION_GELUK',			'TXT_KEY_RELIGION_GELUK_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		5,				'[ICON_RELIGION_GELUK]'),
			('RELIGION_JONANG',			'TXT_KEY_RELIGION_JONANG',			'TXT_KEY_RELIGION_JONANG_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		6,				'[ICON_RELIGION_JONANG]'),
			('RELIGION_BON',			'TXT_KEY_RELIGION_BON',			'TXT_KEY_RELIGION_BON_PEDIA',			'TIBETAN_BUDDHISM_ATLAS',		7,				'[ICON_RELIGION_BON]'),
			('RELIGION_KADAMPA',		'TXT_KEY_RELIGION_KADAMPA',		'TXT_KEY_RELIGION_KADAMPA_PEDIA',		'TIBETAN_BUDDHISM_ATLAS',		8,				'[ICON_RELIGION_KADAMPA]');
