-- IconTextureAtlases
INSERT INTO
	IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
VALUES
	('TIBETAN_BUDDHISM_ATLAS', 256, 'TibetanBuddhism256.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 214, 'TibetanBuddhism214.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 128, 'TibetanBuddhism128.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 80, 'TibetanBuddhism80.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 64, 'TibetanBuddhism64.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 48, 'TibetanBuddhism48.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 32, 'TibetanBuddhism32.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 24, 'TibetanBuddhism24.dds', 3, 3),
	('TIBETAN_BUDDHISM_ATLAS', 16, 'TibetanBuddhism16.dds', 3, 3);

-- IconFontTextures
INSERT INTO
	IconFontTextures (IconFontTexture, IconFontTextureFile)
VALUES
	('ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 'TibetanBuddhism_FontIcons');

-- IconFontMapping
INSERT INTO
	IconFontMapping (IconName, IconFontTexture, IconMapping)
VALUES
	('ICON_RELIGION_NYINGMA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 1),
	('ICON_RELIGION_KARMA_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 2),
	('ICON_RELIGION_DRIKUNG_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 3),
	('ICON_RELIGION_DRUKPA_KAGYU', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 4),
	('ICON_RELIGION_SAKYA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 5),
	('ICON_RELIGION_GELUK', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 6),
	('ICON_RELIGION_JONANG', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 7),
	('ICON_RELIGION_BON', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 8),
	('ICON_RELIGION_KADAMPA', 'ICON_FONT_TEXTURE_TIBETAN_BUDDHISM', 9);
