-- BUILDINGS
INSERT INTO
	Buildings (Type, BuildingClass, Cost, FaithCost, UnlockedByBelief, GoldMaintenance, PrereqTech, Description, Help, Strategy, Civilopedia, ArtDefineTag, MinAreaSize, HurryCostModifier, IconAtlas, NeverCapture, PortraitIndex)
SELECT
	'BUILDING_MENTSIKHANG',
	BuildingClass,
	Cost,
	FaithCost,
	UnlockedByBelief,
	GoldMaintenance,
	PrereqTech,
	'TXT_KEY_BUILDING_MENTSIKHANG',
	'TXT_KEY_BUILDING_MENTSIKHANG_HELP',
	'TXT_KEY_BUILDING_MENTSIKHANG_STRATEGY',
	'TXT_KEY_BUILDING_MENTSIKHANG_TEXT',
	ArtDefineTag,
	MinAreaSize,
	HurryCostModifier,
	'TIBET_THUPTEN_GYATSO_ICON_ATLAS',
	NeverCapture,
	3
FROM
	Buildings
WHERE
	Type = 'BUILDING_LABORATORY';

INSERT INTO
	BuildingClasses (Type, DefaultBuilding, Description)
VALUES
	('BUILDINGCLASS_DIPLOMAT_SCIENCE', 'BUILDING_DIPLOMAT_SCIENCE', 'TXT_KEY_BUILDING_DIPLOMAT_SCIENCE'),
	('BUILDINGCLASS_MENTSIKHANG_FOOD', 'BUILDING_MENTSIKHANG_FOOD', 'TXT_KEY_BUILDING_MENTSIKHANG_FOOD'),
	('BUILDINGCLASS_MENTSIKHANG_PROD', 'BUILDING_MENTSIKHANG_PROD', 'TXT_KEY_BUILDING_MENTSIKHANG_PROD');

INSERT INTO
	Buildings (Type, BuildingClass, Cost, FaithCost, UnlockedByBelief, GoldMaintenance, GreatWorkCount, PrereqTech, Description, Help, Strategy, Civilopedia, ArtDefineTag, MinAreaSize, HurryCostModifier, IconAtlas, NeverCapture, PortraitIndex)
VALUES
	('BUILDING_DIPLOMAT_SCIENCE', 'BUILDINGCLASS_DIPLOMAT_SCIENCE', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_DIPLOMAT_SCIENCE', 'TXT_KEY_BUILDING_DIPLOMAT_SCIENCE_HELP', NULL, NULL, NULL, -1, -1, 'TIBET_THUPTEN_GYATSO_ICON_ATLAS', 1, 0),
	('BUILDING_MENTSIKHANG_FOOD', 'BUILDINGCLASS_MENTSIKHANG_FOOD', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_MENTSIKHANG_FOOD', 'TXT_KEY_BUILDING_MENTSIKHANG_FOOD_HELP', NULL, NULL, NULL, -1, -1, 'TIBET_THUPTEN_GYATSO_ICON_ATLAS', 1, 0),
	('BUILDING_MENTSIKHANG_PROD', 'BUILDINGCLASS_MENTSIKHANG_PROD', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_MENTSIKHANG_PROD', 'TXT_KEY_BUILDING_MENTSIKHANG_PROD_HELP', NULL, NULL, NULL, -1, -1, 'TIBET_THUPTEN_GYATSO_ICON_ATLAS', 1, 0);

INSERT INTO
	Building_YieldChanges (BuildingType, YieldType, Yield)
VALUES
	('BUILDING_DIPLOMAT_SCIENCE', 'YIELD_SCIENCE', 1),
	('BUILDING_MENTSIKHANG_FOOD', 'YIELD_FOOD', 1),
	('BUILDING_MENTSIKHANG_PROD', 'YIELD_PRODUCTION', 1);

-- Building_ClassesNeededInCity
INSERT INTO
	Building_ClassesNeededInCity (BuildingType, BuildingClassType)
SELECT
	'BUILDING_MENTSIKHANG',
	BuildingClassType
FROM
	Building_ClassesNeededInCity
WHERE
	BuildingType = 'BUILDING_LABORATORY';

-- Building_DomainFreeExperiences
INSERT INTO
	Building_DomainFreeExperiences (BuildingType, DomainType, Experience)
SELECT
	'BUILDING_MENTSIKHANG',
	DomainType,
	Experience
FROM
	Building_DomainFreeExperiences
WHERE
	BuildingType = 'BUILDING_LABORATORY';

-- Building_Flavors
INSERT INTO
	Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT
	'BUILDING_MENTSIKHANG',
	FlavorType,
	Flavor
FROM
	Building_Flavors
WHERE
	BuildingType = 'BUILDING_LABORATORY';

INSERT INTO
	Building_Flavors (BuildingType, FlavorType, Flavor)
VALUES
	('BUILDING_MENTSIKHANG', 'FLAVOR_SCIENCE', 25),
	('BUILDING_MENTSIKHANG', 'FLAVOR_CULTURE', 10),
	('BUILDING_MENTSIKHANG', 'FLAVOR_GREAT_PEOPLE', 8);

-- Units
INSERT INTO
	Units (Type, Class, PrereqTech, Combat, RangedCombat, Cost, FaithCost, RequiresFaithPurchaseEnabled, Moves, Range, CombatClass, Domain, Description, Help, Strategy, Civilopedia, MilitarySupport, MilitaryProduction, Pillage, Mechanized, ObsoleteTech, AdvancedStartCost, MinAreaSize, XPValueAttack, XPValueDefense, UnitArtInfo, UnitFlagAtlas, UnitFlagIconOffset, IconAtlas, PortraitIndex, MoveRate)
SELECT
	'UNIT_KUSUNG',
	Class,
	PrereqTech,
	Combat,
	RangedCombat,
	Cost,
	FaithCost,
	RequiresFaithPurchaseEnabled,
	Moves,
	Range,
	CombatClass,
	Domain,
	'TXT_KEY_UNIT_KUSUNG',
	'TXT_KEY_UNIT_KUSUNG_HELP',
	'TXT_KEY_UNIT_KUSUNG_STRATEGY',
	'TXT_KEY_UNIT_KUSUNG_TEXT',
	MilitarySupport,
	MilitaryProduction,
	Pillage,
	Mechanized,
	'TECH_PENICILLIN',
	AdvancedStartCost,
	MinAreaSize,
	XPValueAttack,
	XPValueDefense,
	'ART_DEF_UNIT_KUSUNG',
	'TIBET_THUPTEN_GYATSO_UNIT_FLAG_ATLAS',
	0,
	'TIBET_THUPTEN_GYATSO_ICON_ATLAS',
	2,
	MoveRate
FROM
	Units
WHERE
	Type = 'UNIT_GREAT_WAR_INFANTRY';

-- UnitGameplay2DScripts
INSERT INTO
	UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
SELECT
	'UNIT_KUSUNG',
	SelectionSound,
	FirstSelectionSound
FROM
	UnitGameplay2DScripts
WHERE
	UnitType = 'UNIT_GREAT_WAR_INFANTRY';

-- Unit_AITypes
INSERT INTO
	Unit_AITypes (UnitType, UnitAIType)
SELECT
	'UNIT_KUSUNG',
	UnitAIType
FROM
	Unit_AITypes
WHERE
	UnitType = 'UNIT_GREAT_WAR_INFANTRY';

-- Unit_Flavors
INSERT INTO
	Unit_Flavors (UnitType, FlavorType, Flavor)
SELECT
	'UNIT_KUSUNG',
	FlavorType,
	Flavor
FROM
	Unit_Flavors
WHERE
	UnitType = 'UNIT_GREAT_WAR_INFANTRY';

-- Unit_FreePromotions
INSERT INTO
	Unit_FreePromotions (UnitType, PromotionType)
SELECT
	'UNIT_KUSUNG',
	PromotionType
FROM
	Unit_FreePromotions
WHERE
	UnitType = 'UNIT_GREAT_WAR_INFANTRY';

-- Unit_ClassUpgrades
INSERT INTO
	Unit_ClassUpgrades (UnitType, UnitClassType)
SELECT
	'UNIT_KUSUNG',
	UnitClassType
FROM
	Unit_ClassUpgrades
WHERE
	UnitType = 'UNIT_GREAT_WAR_INFANTRY';

-- Leaders
INSERT INTO
	Leaders (Type, Description, Civilopedia, CivilopediaTag, ArtDefineTag, IconAtlas, PortraitIndex)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_PEDIA', 'TXT_KEY_CIVILOPEDIA_LEADERS_TIBET_THUPTEN_GYATSO', 'Tibet_Thupten_Gyatso_Scene.xml', 'TIBET_THUPTEN_GYATSO_ICON_ATLAS', 1);

UPDATE Leaders
SET
	VictoryCompetitiveness = 8,
	WonderCompetitiveness = 3,
	MinorCivCompetitiveness = 10,
	Boldness = 6,
	DiploBalance = 8,
	WarmongerHate = 2,
	DenounceWillingness = 2,
	DoFWillingness = 10,
	Loyalty = 8,
	Neediness = 4,
	Forgiveness = 6,
	Chattiness = 2,
	Meanness = 5
WHERE
	Type = 'LEADER_TIBET_THUPTEN_GYATSO';

-- Leader_MajorCivApproachBiases
INSERT INTO
	Leader_MajorCivApproachBiases (LeaderType, MajorCivApproachType, Bias)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_WAR', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_HOSTILE', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_DECEPTIVE', 3),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_GUARDED', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_AFRAID', 3),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_FRIENDLY', 7),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MAJOR_CIV_APPROACH_NEUTRAL', 7);

-- Leader_MajorCivApproachBiases
INSERT INTO
	Leader_MinorCivApproachBiases (LeaderType, MinorCivApproachType, Bias)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'MINOR_CIV_APPROACH_IGNORE', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MINOR_CIV_APPROACH_FRIENDLY', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MINOR_CIV_APPROACH_PROTECTIVE', 8),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MINOR_CIV_APPROACH_CONQUEST', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'MINOR_CIV_APPROACH_BULLY', 4);

-- Leader_Flavors
INSERT INTO
	Leader_Flavors (LeaderType, FlavorType, Flavor)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_OFFENSE', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_DEFENSE', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_CITY_DEFENSE', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_MILITARY_TRAINING', 8),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_RECON', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_RANGED', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_MOBILE', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_NAVAL', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_NAVAL_RECON', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_NAVAL_GROWTH', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_NAVAL_TILE_IMPROVEMENT', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_AIR', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_EXPANSION', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_GROWTH', 3),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_TILE_IMPROVEMENT', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_INFRASTRUCTURE', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_PRODUCTION', 7),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_GOLD', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_SCIENCE', 8),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_CULTURE', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_HAPPINESS', 5),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_GREAT_PEOPLE', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_WONDER', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_RELIGION', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_DIPLOMACY', 9),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_SPACESHIP', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_WATER_CONNECTION', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_NUKE', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_USE_NUKE', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_ESPIONAGE', 8),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_AIRLIFT', 2),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_I_TRADE_DESTINATION', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_I_TRADE_ORIGIN', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_I_SEA_TRADE_ROUTE', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_I_LAND_TRADE_ROUTE', 4),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_ARCHAEOLOGY', 6),
	('LEADER_TIBET_THUPTEN_GYATSO', 'FLAVOR_AIR_CARRIER', 4);

-- Diplomacy_Responses
INSERT INTO
	Diplomacy_Responses (LeaderType, ResponseType, Response, Bias)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_AI_DOF_BACKSTAB', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_DENOUNCE_FRIEND%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_ATTACKED_HOSTILE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_ATTACKED_HOSTILE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_ATTACKED_STRONG_HOSTILE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_ATTACKED_HOSTILE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_DEFEATED', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_DEFEATED%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_DOW_GENERIC%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_EXPANSION_SERIOUS_WARNING', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_EXPANSION_SERIOUS_WARNING%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_FIRSTGREETING%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_GREETING_HOSTILE_HELLO%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_GREETING_NEUTRAL_HELLO%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_GREETING_POLITE_HELLO%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_LUXURY_TRADE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_LUXURY_TRADE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_OPEN_BORDERS_EXCHANGE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_OPEN_BORDERS_EXCHANGE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_PLOT_BUYING_SERIOUS_WARNING%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_REQUEST', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_REQUEST%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_RESPONSE_TO_BEING_DENOUNCED%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_TOO_SOON_FOR_DOF', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_TOO_SOON_FOR_DOF%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_TOO_SOON_NO_PEACE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_TOO_SOON_NO_PEACE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_WORK_AGAINST_SOMEONE', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_DENOUNCE%', 500),
	('LEADER_TIBET_THUPTEN_GYATSO', 'RESPONSE_WORK_WITH_US', 'TXT_KEY_LEADER_TIBET_THUPTEN_GYATSO_DEC_FRIENDSHIP%', 500);

-- Leader_Traits
INSERT INTO
	Leader_Traits (LeaderType, TraitType)
VALUES
	('LEADER_TIBET_THUPTEN_GYATSO', 'TRAIT_TIBET_THUPTEN_GYATSO');

-- Traits
INSERT INTO
	Traits (Type, Description, ShortDescription)
VALUES
	('TRAIT_TIBET_THUPTEN_GYATSO', 'TXT_KEY_TRAIT_TIBET_THUPTEN_GYATSO', 'TXT_KEY_TRAIT_TIBET_THUPTEN_GYATSO_SHORT');

-- Civilizations
INSERT INTO
	Civilizations (Type, DerivativeCiv, SoundtrackTag, MapImage, DawnOfManQuote, DawnOfManImage, Description, ShortDescription, Adjective, Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, IconAtlas, PortraitIndex, AlphaIconAtlas)
SELECT
	'CIVILIZATION_TIBET_THUPTEN_GYATSO',
	'CIVILIZATION_MONGOL',
	'Mongol',
	'Map_Tibet_Thupten_Gyatso.dds',
	'TXT_KEY_CIV_DAWN_TIBET_THUPTEN_GYATSO_TEXT',
	'DOM_Tibet_Thupten_Gyatso.dds',
	'TXT_KEY_CIVILIZATION_TIBET_THUPTEN_GYATSO_DESC',
	'TXT_KEY_CIVILIZATION_TIBET_THUPTEN_GYATSO_SHORT_DESC',
	'TXT_KEY_CIVILIZATION_TIBET_THUPTEN_GYATSO_ADJECTIVE',
	Civilopedia,
	CivilopediaTag,
	'PLAYERCOLOR_TIBET_THUPTEN_GYATSO',
	ArtDefineTag,
	ArtStyleType,
	ArtStyleSuffix,
	ArtStylePrefix,
	'TIBET_THUPTEN_GYATSO_ICON_ATLAS',
	0,
	'TIBET_THUPTEN_GYATSO_ALPHA_ATLAS'
FROM
	Civilizations
WHERE
	Type = 'CIVILIZATION_MONGOL';

-- Civilization_CityNames
INSERT INTO
	Civilization_CityNames (CivilizationType, CityName)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_01'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_02'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_03'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_04'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_05'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_06'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_07'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_08'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_09'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_10'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_11'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_12'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_13'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_14'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_15'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_16'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_17'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_18'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_19'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_20'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_21'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_22'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_23'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_24'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_25'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_26'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_27'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_28'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_29'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_30'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_31'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_32'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_33'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_34'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_35'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_36'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_37'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_38'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_39'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_40'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_41'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_42'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_43'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_44'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_45'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_46'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_47'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_48'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_49'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_50'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_51'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_52'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_53'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_54'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_CITY_NAME_TIBET_THUPTEN_GYATSO_55');

-- Civilization_FreeBuildingClasses
INSERT INTO
	Civilization_FreeBuildingClasses (CivilizationType, BuildingClassType)
SELECT
	'CIVILIZATION_TIBET_THUPTEN_GYATSO',
	BuildingClassType
FROM
	Civilization_FreeBuildingClasses
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_FreeTechs
INSERT INTO
	Civilization_FreeTechs (CivilizationType, TechType)
SELECT
	'CIVILIZATION_TIBET_THUPTEN_GYATSO',
	TechType
FROM
	Civilization_FreeTechs
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_FreeUnits
INSERT INTO
	Civilization_FreeUnits (CivilizationType, UnitClassType, Count, UnitAIType)
SELECT
	'CIVILIZATION_TIBET_THUPTEN_GYATSO',
	UnitClassType,
	Count,
	UnitAIType
FROM
	Civilization_FreeUnits
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_Leaders
INSERT INTO
	Civilization_Leaders (CivilizationType, LeaderheadType)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'LEADER_TIBET_THUPTEN_GYATSO');

-- Civilization_BuildingClassOverrides
INSERT INTO
	Civilization_BuildingClassOverrides (CivilizationType, BuildingClassType, BuildingType)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'BUILDINGCLASS_LABORATORY', 'BUILDING_MENTSIKHANG');

-- Civilization_UnitClassOverrides
INSERT INTO
	Civilization_UnitClassOverrides (CivilizationType, UnitClassType, UnitType)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'UNITCLASS_GREAT_WAR_INFANTRY', 'UNIT_KUSUNG');

-- Civilization_Religions
INSERT INTO
	Civilization_Religions (CivilizationType, ReligionType)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'RELIGION_BUDDHISM');

-- Civilization_SpyNames
INSERT INTO
	Civilization_SpyNames (CivilizationType, SpyName)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_0'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_1'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_2'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_3'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_4'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_5'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_6'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_7'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_8'),
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'TXT_KEY_SPY_NAME_TIBET_THUPTEN_GYATSO_9');

-- Civilization_Start_Region_Priority
INSERT INTO
	Civilization_Start_Region_Priority (CivilizationType, RegionType)
VALUES
	('CIVILIZATION_TIBET_THUPTEN_GYATSO', 'REGION_HILLS');
