-- FEATURES
-- Sacred Peak Feature
INSERT INTO Features
	(Type, Description, Civilopedia, ArtDefineTag, Movement, Defense, NoImprovement, PortraitIndex, IconAtlas)
VALUES
	('FEATURE_SACRED_PEAK', 'TXT_KEY_FEATURE_SACRED_PEAK', 'TXT_KEY_FEATURE_SACRED_PEAK_PEDIA', 'ART_DEF_FEATURE_SACRED_PEAK', 0, 0, 1, 0, 'YARLUNG_NYATRI_ICON_ATLAS');

-- BUILDINGS
-- Dummy buildings for Sacred Peak bonuses
INSERT INTO
	BuildingClasses (Type, DefaultBuilding, Description)
VALUES
	('BUILDINGCLASS_SACRED_PEAK', 'BUILDING_SACRED_PEAK', 'TXT_KEY_BUILDING_SACRED_PEAK'),
	('BUILDINGCLASS_SACRED_PEAK_DOUBLED', 'BUILDING_SACRED_PEAK_DOUBLED', 'TXT_KEY_BUILDING_SACRED_PEAK_DOUBLED'),
	('BUILDINGCLASS_DUMMY_SKY_BURIAL_CULTURE', 'BUILDING_DUMMY_SKY_BURIAL_CULTURE', 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_CULTURE'),
	('BUILDINGCLASS_DUMMY_SKY_BURIAL_FAITH', 'BUILDING_DUMMY_SKY_BURIAL_FAITH', 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_FAITH'),
	('BUILDINGCLASS_DUMMY_SKY_BURIAL_TOURISM', 'BUILDING_DUMMY_SKY_BURIAL_TOURISM', 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_TOURISM'),
	('BUILDINGCLASS_CHOD_CEREMONY', 'BUILDING_CHOD_CEREMONY', 'TXT_KEY_BUILDING_CHOD_CEREMONY'),
	('BUILDINGCLASS_CHOD_CEREMONY_MOUNTAIN', 'BUILDING_CHOD_CEREMONY_MOUNTAIN', 'TXT_KEY_BUILDING_CHOD_CEREMONY_MOUNTAIN'),
	('BUILDINGCLASS_CHOD_CEREMONY_ARTIST',   'BUILDING_CHOD_CEREMONY_ARTIST',   'TXT_KEY_BUILDING_CHOD_CEREMONY_ARTIST'),
	('BUILDINGCLASS_CHOD_CEREMONY_WRITER',   'BUILDING_CHOD_CEREMONY_WRITER',   'TXT_KEY_BUILDING_CHOD_CEREMONY_WRITER'),
	('BUILDINGCLASS_CHOD_CEREMONY_MUSICIAN', 'BUILDING_CHOD_CEREMONY_MUSICIAN', 'TXT_KEY_BUILDING_CHOD_CEREMONY_MUSICIAN'),
	('BUILDINGCLASS_CHOD_CEREMONY_TOURISM', 'BUILDING_CHOD_CEREMONY_TOURISM', 'TXT_KEY_BUILDING_CHOD_CEREMONY_TOURISM');

INSERT INTO
	Buildings (Type, BuildingClass, Cost, FaithCost, UnlockedByBelief, GoldMaintenance, GreatWorkCount, PrereqTech, Description, Help, Strategy, Civilopedia, ArtDefineTag, MinAreaSize, HurryCostModifier, IconAtlas, NeverCapture, PortraitIndex, GreatWorksTourismModifier)
VALUES
	('BUILDING_SACRED_PEAK', 'BUILDINGCLASS_SACRED_PEAK', -1, -1, 0, 0, 0, NULL, 'TXT_KEY_BUILDING_SACRED_PEAK', 'TXT_KEY_BUILDING_SACRED_PEAK_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_SACRED_PEAK_DOUBLED', 'BUILDINGCLASS_SACRED_PEAK_DOUBLED', -1, -1, 0, 0, 0, NULL, 'TXT_KEY_BUILDING_SACRED_PEAK_DOUBLED', 'TXT_KEY_BUILDING_SACRED_PEAK_DOUBLED_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY', 'BUILDINGCLASS_CHOD_CEREMONY', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY', 'TXT_KEY_BUILDING_CHOD_CEREMONY_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY_MOUNTAIN', 'BUILDINGCLASS_CHOD_CEREMONY_MOUNTAIN', -1, -1, 0, 0, 0, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY_MOUNTAIN', 'TXT_KEY_BUILDING_CHOD_CEREMONY_MOUNTAIN_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY_ARTIST',   'BUILDINGCLASS_CHOD_CEREMONY_ARTIST',   -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY_ARTIST',   'TXT_KEY_BUILDING_CHOD_CEREMONY_ARTIST_HELP',   NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY_WRITER',   'BUILDINGCLASS_CHOD_CEREMONY_WRITER',   -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY_WRITER',   'TXT_KEY_BUILDING_CHOD_CEREMONY_WRITER_HELP',   NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY_MUSICIAN', 'BUILDINGCLASS_CHOD_CEREMONY_MUSICIAN', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY_MUSICIAN', 'TXT_KEY_BUILDING_CHOD_CEREMONY_MUSICIAN_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_CHOD_CEREMONY_TOURISM', 'BUILDINGCLASS_CHOD_CEREMONY_TOURISM', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_CHOD_CEREMONY_TOURISM', 'TXT_KEY_BUILDING_CHOD_CEREMONY_TOURISM_HELP', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 50),
	('BUILDING_DUMMY_SKY_BURIAL_CULTURE', 'BUILDINGCLASS_DUMMY_SKY_BURIAL_CULTURE', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_CULTURE', '', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_DUMMY_SKY_BURIAL_FAITH', 'BUILDINGCLASS_DUMMY_SKY_BURIAL_FAITH', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_FAITH', '', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0),
	('BUILDING_DUMMY_SKY_BURIAL_TOURISM', 'BUILDINGCLASS_DUMMY_SKY_BURIAL_TOURISM', -1, -1, 0, 0, -1, NULL, 'TXT_KEY_BUILDING_DUMMY_SKY_BURIAL_TOURISM', '', NULL, NULL, NULL, -1, -1, 'YARLUNG_NYATRI_ICON_ATLAS', 1, 0, 0);

-- Building Yields for Sacred Peaks
INSERT INTO
	Building_YieldChanges (BuildingType, YieldType, Yield)
VALUES
	('BUILDING_SACRED_PEAK', 'YIELD_CULTURE', 3),
	('BUILDING_SACRED_PEAK', 'YIELD_FAITH', 3),
	('BUILDING_SACRED_PEAK_DOUBLED', 'YIELD_CULTURE', 6),
	('BUILDING_SACRED_PEAK_DOUBLED', 'YIELD_FAITH', 6),
	('BUILDING_DUMMY_SKY_BURIAL_CULTURE', 'YIELD_CULTURE', 1),
	('BUILDING_DUMMY_SKY_BURIAL_FAITH', 'YIELD_FAITH', 1);


INSERT INTO
	Building_ThemingBonuses (BuildingType, Bonus)
VALUES
	('BUILDING_CHOD_CEREMONY', 2);

-- UNITS
-- Pawo (Great Musician replacement)
INSERT INTO
	Units (Type, Class, PrereqTech, Combat, RangedCombat, Cost, FaithCost, RequiresFaithPurchaseEnabled, Moves, Range, CombatClass, Domain, DefaultUnitAI, UnitArtInfoEraVariation, Description, Help, Strategy, Civilopedia, MilitarySupport, MilitaryProduction, Pillage, Mechanized, ObsoleteTech, AdvancedStartCost, MinAreaSize, XPValueAttack, XPValueDefense,  Special, OneShotTourism, OneShotTourismPercentOthers, UnitArtInfo, UnitFlagAtlas, UnitFlagIconOffset, IconAtlas, PortraitIndex, MoveRate)
SELECT
	'UNIT_PAWO',
	'UNITCLASS_MUSICIAN',
	PrereqTech,
	Combat,
	RangedCombat,
	Cost,
	FaithCost,
	RequiresFaithPurchaseEnabled,
	Moves,
	Range,
	CombatClass,
	Domain,
	DefaultUnitAI,
	0,
	'TXT_KEY_UNIT_PAWO',
	'TXT_KEY_UNIT_PAWO_HELP',
	'TXT_KEY_UNIT_PAWO_STRATEGY',
	'TXT_KEY_UNIT_PAWO_TEXT',
	MilitarySupport,
	MilitaryProduction,
	Pillage,
	Mechanized,
	ObsoleteTech,
	AdvancedStartCost,
	MinAreaSize,
	XPValueAttack,
	XPValueDefense,
	Special,
	OneShotTourism,
	OneShotTourismPercentOthers,
	'ART_DEF_UNIT_GREAT_MUSICIAN',
	'YARLUNG_NYATRI_UNIT_FLAG_ATLAS',
	0,
	'YARLUNG_NYATRI_ICON_ATLAS',
	2,
	MoveRate
FROM
	Units
WHERE
	Type = 'UNIT_MUSICIAN';

-- IMPROVEMENTS
INSERT INTO
	Improvements (Type, Description, Help, Civilopedia, ArtDefineTag, RequiresFeature, RequiresImprovement, DestroyedWhenPillaged, Permanent, OutsideBorders, GraphicalOnly, IconAtlas, PortraitIndex, SpecificCivRequired, CivilizationType, NoTwoAdjacent)
VALUES
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TXT_KEY_IMPROVEMENT_SKY_BURIAL_GROUND', 'TXT_KEY_IMPROVEMENT_SKY_BURIAL_GROUND_HELP', 'TXT_KEY_IMPROVEMENT_SKY_BURIAL_GROUND_TEXT', 'ART_DEF_IMPROVEMENT_SKY_BURIAL_GROUND', 0, 0, 0, 1, 0, 3, 'YARLUNG_NYATRI_ICON_ATLAS', 3, 1, 'CIVILIZATION_YARLUNG_PUGYEL', 1);

INSERT INTO
	Improvement_Yields (ImprovementType, YieldType, Yield)
VALUES
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'YIELD_CULTURE', 2),
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'YIELD_FAITH', 2);

-- Improvement_ValidTerrains
INSERT INTO
	Improvement_ValidTerrains (ImprovementType, TerrainType)
VALUES
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TERRAIN_HILL'),
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TERRAIN_TUNDRA'),
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TERRAIN_SNOW'),
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TERRAIN_GRASS'),
	('IMPROVEMENT_SKY_BURIAL_GROUND', 'TERRAIN_PLAINS');

INSERT INTO Builds
	(Type, PrereqTech, Time, ImprovementType, Description, Help, Recommendation, EntityEvent, HotKey, OrderPriority, CtrlDown, IconIndex, IconAtlas)
VALUES
	('BUILD_SKY_BURIAL_GROUND', 'TECH_POTTERY', 400, 'IMPROVEMENT_SKY_BURIAL_GROUND', 'TXT_KEY_BUILD_SKY_BURIAL_GROUND', 'TXT_KEY_BUILD_SKY_BURIAL_GROUND_HELP', 'TXT_KEY_BUILD_SKY_BURIAL_GROUND_REC', 'ENTITY_EVENT_BUILD', 'KB_N', 96, 1, 0, 'YARLUNG_NYATRI_UI_ATLAS');

INSERT INTO BuildFeatures
	(BuildType, FeatureType, PrereqTech, Time, Production, Remove)
VALUES
	('BUILD_SKY_BURIAL_GROUND', 'FEATURE_JUNGLE', 'TECH_BRONZE_WORKING', 700, NULL, 0),
	('BUILD_SKY_BURIAL_GROUND', 'FEATURE_FOREST', 'TECH_MINING', 400, 20, 0),
	('BUILD_SKY_BURIAL_GROUND', 'FEATURE_MARSH', 'TECH_MASONRY', 600, NULL, 0);

INSERT INTO
	Unit_Builds (UnitType, BuildType)
VALUES
	('UNIT_WORKER', 'BUILD_SKY_BURIAL_GROUND');

-- LEADERS
INSERT INTO
	Leaders (Type, Description, Civilopedia, CivilopediaTag, ArtDefineTag, IconAtlas, PortraitIndex)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_PEDIA', 'TXT_KEY_CIVILOPEDIA_LEADERS_NYATRI_TSENPO', 'Nyatri_Tsenpo_Scene.xml', 'YARLUNG_NYATRI_ICON_ATLAS', 1);

UPDATE Leaders
SET
	VictoryCompetitiveness = 7,
	WonderCompetitiveness = 8,
	MinorCivCompetitiveness = 3,
	Boldness = 4,
	DiploBalance = 7,
	WarmongerHate = 5,
	DenounceWillingness = 3,
	DoFWillingness = 8,
	Loyalty = 9,
	Neediness = 3,
	Forgiveness = 7,
	Chattiness = 4,
	Meanness = 4
WHERE
	Type = 'LEADER_YARLUNG_NYATRI_TSENPO';

-- Leader_MajorCivApproachBiases
INSERT INTO
	Leader_MajorCivApproachBiases (LeaderType, MajorCivApproachType, Bias)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_WAR', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_HOSTILE', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_DECEPTIVE', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_GUARDED', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_AFRAID', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_FRIENDLY', 8),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MAJOR_CIV_APPROACH_NEUTRAL', 7);

-- Leader_MinorCivApproachBiases
INSERT INTO
	Leader_MinorCivApproachBiases (LeaderType, MinorCivApproachType, Bias)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MINOR_CIV_APPROACH_IGNORE', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MINOR_CIV_APPROACH_FRIENDLY', 7),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MINOR_CIV_APPROACH_PROTECTIVE', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MINOR_CIV_APPROACH_CONQUEST', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'MINOR_CIV_APPROACH_BULLY', 2);

-- Leader_Flavors
INSERT INTO
	Leader_Flavors (LeaderType, FlavorType, Flavor)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_OFFENSE', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_DEFENSE', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_CITY_DEFENSE', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_MILITARY_TRAINING', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_RECON', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_RANGED', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_MOBILE', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_NAVAL', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_NAVAL_RECON', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_NAVAL_GROWTH', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_NAVAL_TILE_IMPROVEMENT', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_AIR', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_EXPANSION', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_GROWTH', 7),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_TILE_IMPROVEMENT', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_INFRASTRUCTURE', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_PRODUCTION', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_GOLD', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_SCIENCE', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_CULTURE', 9),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_HAPPINESS', 7),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_GREAT_PEOPLE', 10),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_WONDER', 8),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_RELIGION', 9),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_DIPLOMACY', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_SPACESHIP', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_WATER_CONNECTION', 2),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_NUKE', 1),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_USE_NUKE', 1),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_ESPIONAGE', 4),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_AIRLIFT', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_I_TRADE_DESTINATION', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_I_TRADE_ORIGIN', 5),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_I_SEA_TRADE_ROUTE', 3),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_I_LAND_TRADE_ROUTE', 6),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_ARCHAEOLOGY', 8),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'FLAVOR_AIR_CARRIER', 3);

-- Diplomacy_Responses
INSERT INTO
	Diplomacy_Responses (LeaderType, ResponseType, Response, Bias)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_AI_DOF_BACKSTAB', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_DENOUNCE_FRIEND%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_ATTACKED_HOSTILE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_ATTACKED_HOSTILE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_ATTACKED_STRONG_HOSTILE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_ATTACKED_HOSTILE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_DEFEATED', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_DEFEATED%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_DOW_GENERIC', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_DOW_GENERIC%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_EXPANSION_SERIOUS_WARNING', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_EXPANSION_SERIOUS_WARNING%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_FIRST_GREETING', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_FIRSTGREETING%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_GREETING_HOSTILE_HELLO', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_GREETING_HOSTILE_HELLO%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_GREETING_NEUTRAL_HELLO', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_GREETING_NEUTRAL_HELLO%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_GREETING_POLITE_HELLO', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_GREETING_POLITE_HELLO%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_LUXURY_TRADE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_LUXURY_TRADE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_OPEN_BORDERS_EXCHANGE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_OPEN_BORDERS_EXCHANGE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_PLOT_BUYING_SERIOUS_WARNING%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_REQUEST', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_REQUEST%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_RESPONSE_TO_BEING_DENOUNCED%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_TOO_SOON_FOR_DOF', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_TOO_SOON_FOR_DOF%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_TOO_SOON_NO_PEACE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_TOO_SOON_NO_PEACE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_WORK_AGAINST_SOMEONE', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_DENOUNCE%', 500),
	('LEADER_YARLUNG_NYATRI_TSENPO', 'RESPONSE_WORK_WITH_US', 'TXT_KEY_LEADER_YARLUNG_NYATRI_TSENPO_DEC_FRIENDSHIP%', 500);

-- Leader_Traits
INSERT INTO
	Leader_Traits (LeaderType, TraitType)
VALUES
	('LEADER_YARLUNG_NYATRI_TSENPO', 'TRAIT_CORD_HEAVEN_EARTH');

-- Traits
INSERT INTO
	Traits (Type, Description, ShortDescription)
VALUES
	('TRAIT_CORD_HEAVEN_EARTH', 'TXT_KEY_TRAIT_CORD_HEAVEN_EARTH', 'TXT_KEY_TRAIT_CORD_HEAVEN_EARTH_SHORT');

-- CIVILIZATIONS
INSERT INTO
	Civilizations (Type, DerivativeCiv, SoundtrackTag, MapImage, DawnOfManQuote, DawnOfManImage, Description, ShortDescription, Adjective, Civilopedia, CivilopediaTag, DefaultPlayerColor, ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, IconAtlas, PortraitIndex, AlphaIconAtlas)
SELECT
	'CIVILIZATION_YARLUNG_PUGYEL',
	'CIVILIZATION_MONGOL',
	'Mongol',
	'Map_Yarlung_Pugyel.dds',
	'TXT_KEY_CIV_DAWN_YARLUNG_PUGYEL_TEXT',
	'DOM_Yarlung_Pugyel.dds',
	'TXT_KEY_CIVILIZATION_YARLUNG_PUGYEL_DESC',
	'TXT_KEY_CIVILIZATION_YARLUNG_PUGYEL_SHORT_DESC',
	'TXT_KEY_CIVILIZATION_YARLUNG_PUGYEL_ADJECTIVE',
	Civilopedia,
	CivilopediaTag,
	'PLAYERCOLOR_YARLUNG_NYATRI',
	ArtDefineTag,
	ArtStyleType,
	ArtStyleSuffix,
	ArtStylePrefix,
	'YARLUNG_NYATRI_ICON_ATLAS',
	0,
	'YARLUNG_NYATRI_ALPHA_ATLAS'
FROM
	Civilizations
WHERE
	Type = 'CIVILIZATION_MONGOL';

-- Civilization_CityNames
INSERT INTO
	Civilization_CityNames (CivilizationType, CityName)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_01'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_02'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_03'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_04'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_05'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_06'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_07'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_08'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_09'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_10'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_11'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_12'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_13'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_14'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_15'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_16'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_17'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_18'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_19'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_20'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_21'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_22'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_23'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_24'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_CITY_NAME_YARLUNG_25');

-- Civilization_FreeBuildingClasses
INSERT INTO
	Civilization_FreeBuildingClasses (CivilizationType, BuildingClassType)
SELECT
	'CIVILIZATION_YARLUNG_PUGYEL',
	BuildingClassType
FROM
	Civilization_FreeBuildingClasses
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_FreeTechs
INSERT INTO
	Civilization_FreeTechs (CivilizationType, TechType)
SELECT
	'CIVILIZATION_YARLUNG_PUGYEL',
	TechType
FROM
	Civilization_FreeTechs
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_FreeUnits
INSERT INTO
	Civilization_FreeUnits (CivilizationType, UnitClassType, Count, UnitAIType)
SELECT
	'CIVILIZATION_YARLUNG_PUGYEL',
	UnitClassType,
	Count,
	UnitAIType
FROM
	Civilization_FreeUnits
WHERE
	CivilizationType = 'CIVILIZATION_MONGOL';

-- Civilization_Leaders
INSERT INTO
	Civilization_Leaders (CivilizationType, LeaderheadType)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'LEADER_YARLUNG_NYATRI_TSENPO');

-- Civilization_UnitClassOverrides
INSERT INTO
	Civilization_UnitClassOverrides (CivilizationType, UnitClassType, UnitType)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'UNITCLASS_MUSICIAN', 'UNIT_PAWO');

-- Civilization_Religions
INSERT INTO
	Civilization_Religions (CivilizationType, ReligionType)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'RELIGION_BUDDHISM');

-- Civilization_SpyNames
INSERT INTO
	Civilization_SpyNames (CivilizationType, SpyName)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_0'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_1'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_2'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_3'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_4'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_5'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_6'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_7'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_8'),
	('CIVILIZATION_YARLUNG_PUGYEL', 'TXT_KEY_SPY_NAME_YARLUNG_9');

-- Civilization_Start_Region_Priority
INSERT INTO
	Civilization_Start_Region_Priority (CivilizationType, RegionType)
VALUES
	('CIVILIZATION_YARLUNG_PUGYEL', 'REGION_HILLS');
